### ISSUE TITLE
[WooMinecraft] java.lang.IllegalStateException:

### ISSUE THREAD

**Issue by ProxTricky** [WooMinecraft/WooMinecraft#242] opened 2021-03-21 18:06 UTC
**Log Link:** https://pastebin.com/kHbAhCFB

### Server Information:
* **Host:** dedicated server on debian
* **URL:** play.satyria.fr
* **WordPress URL:** https://satyria.fr

### Config.yml
lang: "en"
update_interval: 1500
url: "http://satyria.fr"
key: "abcdef"
debug: false

So I don't know why it's not working... here's the error that we have. We can make the purchase on our wordpress but we don't receive anything :/
Any idea ?

**Comment by JayWood** [comment] 2021-03-23 01:29
If you hit `https://satyria.fr/wp-json/wmc/v1/server/<your key>` you should see a bunch of garbled information. I hit it in the browser and it seems to load for me ( minus your key )

I can't see anything that screams cloudflare so I'm honestly not sure what the issue is. In your pastebin you're getting the following:
```
Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
```

This means the response from your web server was not a JSON object. You can try setting `debug: true` to get more information in your log.

**Comment by JayWood** [comment] 2021-03-31 15:14
No reply in 7+ days closing and assume resolved.

**Closed by JayWood** 2021-03-31 15:14 UTC
Labels: Question, Server Config
