### ISSUE TITLE
Woo register swipes rest of configuration

### ISSUE THREAD

**Issue by HappyHarm** [WooMinecraft/WooMinecraft#73] opened 2016-02-08 13:46 UTC
Hi, same issue as I reported some weeks ago. Just tried the newest build but it looks like the config is getting swiped again. 
#60 
![](http://i.imgur.com/kgp5R7s.png)

**Comment by TekkitCommando** [comment] 2016-02-08 13:50
See my comments on the closed issue.

**Comment by HappyHarm** [comment] 2016-02-08 13:53
Answered that one ;) Maybe we should use the open one now or open the old issue again xD

**Comment by JayWood** [comment] 2016-02-08 14:01
Duplicate of #60 re-opened, closing this one.

**Closed by JayWood** 2016-02-08 14:01 UTC
