### ISSUE TITLE
/woo check crash server

### ISSUE THREAD

**Issue by Harryols** [WooMinecraft/WooMinecraft#162] opened 2017-07-15 13:09 UTC
//////////////////   
// You can delete the following   
// In order for me to better serve your support request, please fill out the following information.   
// Please use pastebin http://pastebin.com/ or gists https://gist.github.com/ for your logs, DO NOT PASTE them in a support request.   
// Refer to the following link for proper config.yml setup fields - https://github.com/WooMinecraft/WooMinecraft#config   
// 
// YOU MUST ACTIVATE DEBUG IN YOUR CONFIG AND PROVIDE THAT LOG
//   
// Fields below this line are required - failure to fill these in will result in your issue being tagged low-priority.   
/////////////////   

**Log Link: https://pastebin.com/UL8Zgdpy** 

### Server Information:
* **Host: harryo.dk **
* **URL: https://harryo.dk **
* **WordPress URL: https://harryo.dk**

### Config.yml
* **url: https://pastebin.com/TJ6GYRmH**

**Comment by spannerman79** [comment] 2017-07-15 13:31
>YOU MUST ACTIVATE DEBUG IN YOUR CONFIG AND PROVIDE THAT LOG
?

**Comment by Harryols** [comment] 2017-07-15 13:36
Where can I find to log?

**Comment by Harryols** [comment] 2017-07-15 13:45
log: https://pastebin.com/UL8Zgdpy

**Comment by spannerman79** [comment] 2017-07-15 13:52
```
[15:43:38] [Server thread/INFO]: Harry2109 issued server command: /woo
[15:43:43] [Server thread/INFO]: Harry2109 issued server command: /woo check
[15:44:12] [Thread-3/INFO]: Stopping server
```
Did you do what was asked? 

>**YOU MUST ACTIVATE DEBUG** IN YOUR CONFIG AND PROVIDE THAT LOG

I see no debug text that woominecraft puts into console.

**Comment by JayWood** [comment] 2017-07-15 13:53
Set `debug: true` in the config.yml of the WMC plugin. Provide that log. Until then, there's not enough information for me to say "yea this is it...." what I can say is this isn't officially tested on Spigot though. ( but I know users who have used it without issue )

**Comment by Harryols** [comment] 2017-07-15 14:03
As you can see in my config.yml I have set debug to true, it seems to me like the function is not working.

**Comment by Harryols** [comment] 2017-07-15 14:06
I just got something: https://pastebin.com/LuXFDMLL

**Comment by spannerman79** [comment] 2017-07-15 14:43
Issue is on your end with how your server setup.
I on purpose did the exact same thing - placing https://google.com and a random string into key and guess what - it didn't crash the server

`This server is running CraftBukkit version git-Spigot-21fe707-e1ebe52 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)`

Using `WooMinecraft-1.1.1-B1.8.8-R0.1.jar` from https://github.com/WooMinecraft/WooMinecraft/releases/tag/1.1.1

Issue is with your end @Harryols 

Please close this @JayWood - user created issue. Not a WMC issue.

**Comment by Harryols** [comment] 2017-07-15 14:49
That didn't help me, how can I make this plugin work?
Do I need to donate to make you help me, I really want to use this plugin.

**Comment by Harryols** [comment] 2017-07-15 15:50
This plugin is not user friendly at all (seems like it's half done).
It will only work on some server setups, and you can't get help because the plugin is not compatible with most servers.

**Comment by spannerman79** [comment] 2017-07-15 18:17
> This plugin is not user friendly in any way (seems like it's half done).

As is your input to try and resolve issues. Take for example https://github.com/WooMinecraft/WooMinecraft/issues/141

> It will only work on some server setups, and you can't get help because the plugin is not compatible with most servers.

Do you even bother doing any troubleshooting yourself?  I already (https://github.com/WooMinecraft/WooMinecraft/issues/162#issuecomment-315538432) tried to reproduce your issue with what you gave and I was unable to.  Therefore trying to debug your issue is next to impossible without you trying to test things yourself.

**Comment by Harryols** [comment] 2017-07-15 18:55
I have worked the whole day with this plugin with every version and different domains.

**Comment by JayWood** [comment] 2017-07-16 04:30
Due to the nature of open source, no one can guarantee compatibility with EVERY server build. Furthermore these builds were tested with BUKKIT not spigot.

The problem we face as developers, is there's no one way to test every scenario. Take this into account when opening support questions for WMC.

There are two aspects to this plugin - Java and PHP. One on the Minecraft side, and one on the WordPress side. WordPress must communicate with Java by sending data between the two. Every build is tested on Bukkit prior being tagged as stable.

Above all, I work on this plugin, and the support, in my own time. I do NOT get paid to handle this. With that being said, this plugin is open source, as is ALL code associated with it. You're free to use/modify it as you see fit, if you lack the capabilities to do so, either pay someone else to do it for you, or find another solution.

### Things to check
* Verify you can get a response from your server via a system such as PostMan ( basically test your API results )
* Again this plugin is NOT tested/built against spigot, good luck there.
* Try your URL with and without https, it's possible your certificate issuer is just wrong.
* Know I've not tested this with a .dk domain.
* See here - https://github.com/WooMinecraft/WooMinecraft/blob/master/src/main/java/com/plugish/woominecraft/Commands/WooCommand.java#L38 It's possible that the build of spigot you're using is screwing with warning throws, or that my implementation of them is just wrong for spigot. ( again this wasn't tested in spigot )

### Donations
Know that I don't do 'donations'. I'm a developer, as I said I work on this plugin in my own time, and I'm not going to ransom a bug for money, that's just immoral.

I don't mind donations simply because you like the plugin, hell I wouldn't mind getting paid to build features, but I do not currently; nor will I ever, require a donation to fix something.

### Unfortunate conclusion
Your server, is just that, your server. I do not have access, and therefore I cannot just 'fix' this for you. Every environment is different.

The ONLY way for me to fix this issue specifically for you is to get full `root` access to both servers via SSH. And to do that it takes time, and a contract ( yea I'm not kidding ), which then gets into hourly fees, and sorry to be blunt, but the gaming community typically will not pay my hourly fees. After all, this plugin is Free, so YOU can get paid to host your server.

Overall, this boils down to the fact that no testing has been done on `Spigot` specifically. Regardless of what version of Bukkit it implements, the wrapper is STILL spigot.

**Closed by JayWood** 2017-07-16 04:30 UTC

**Comment by Harryols** [comment] 2017-07-16 14:10
I understand and will further experiment with the plugin.
I really want this plugin on my server.
