### ISSUE TITLE
WooMinecraft Translated by Language Files

### ISSUE THREAD

**Issue by TekkitCommando** [WooMinecraft/WooMinecraft#29] opened 2015-08-27 12:48 UTC
Instead of a messages.yml file it will us a language file such as english.yml, german.yml, spanish.yml and you can set the language file name in the config :)

**Comment by HappyHarm** [comment] 2015-09-23 16:23
Is there already a format for this? Then I will start adding a dutch language file :P

**Comment by TekkitCommando** [comment] 2015-09-25 19:15
not yet, i will add one to the wiki :)

**Comment by JayWood** [comment] 2015-12-03 21:06
Duplicate of #25 closing that one merging here.

**Comment by JayWood** [comment] 2015-12-13 01:11
Fixed as of above commit, closing.

**Closed by JayWood** 2015-12-13 01:11 UTC
Labels: Change of Plans, Enhancement: Woo Minecraft (Java)
