### ISSUE TITLE
Getting to much items after ordering. 

### ISSUE THREAD

**Issue by Warfacenl** [WooMinecraft/WooMinecraft#82] opened 2016-03-28 15:58 UTC
Hello, i am trying to get ur plugin working with my website, i am getting this error in my Multicraft console: Latest version 1.9 spigot

[WooMinecraft] A JSONObject text must begin with '{' at 2 [character 3 line 1]

I have put this in my Product: http://prntscr.com/al5byq

**Comment by TekkitCommando** [comment] 2016-03-28 18:15
We have gotten this issue before @JayWood is working on an update to the Java side of WooMinecraft.

**Comment by Warfacenl** [comment] 2016-03-28 18:22
Ok i fixed that problem i forgot to change the config in the server:

`# Set this to the desired language file you wish to load.
#
# If your l10n is not available but one is that you know how to speak,consider
# contributing to this plugin at https://github.com/WooMinecraft/WooMinecraft/
lang: nl

# This is how often, in seconds, the server will contact your WordPress installation
# to see if there are donations that need made.
update_interval: 1500

# You must set this to your WordPress site URL.  If you installed WordPress in a
# subdirectory, it should point there.
url: www.unitedclan.net

# This must match the WordPress key in your admin panel for WooMinecraft
# For security purposes, you MUST NOT leave this empty.
key: mykey `


but now i am getting this: 
28.03 20:16:50 [Server] INFO [WooMinecraft]  Geen aankopen beschikbaar - Probeer het later nog eens.
28.03 20:17:22 [Server] WARN [WooMinecraft] no protocol: www.unitedclan.netoo_minecraft=check&key=mykey

**Comment by Warfacenl** [comment] 2016-03-28 19:29
OK so the next thing i have the donate done after some struggeling, now it is giving the items but only to the owner after a server restart and hes doing it a few times if only 1 donation came in. Is there a premission error?

**Comment by JayWood** [comment] 2016-03-28 20:52
@Warfacenl not entirely sure why you would get more than one delivery.  However I haven't tested the 'nl' language for donations. If the QTY of the order was set to 6 ( ie bought 6 items ) then yes, you would get the command 6 times.

If that is not the case, we will need to look deeper into the code and will need screenshots to accompany this bug. So, if you can take screenshots of EVERY screen throughout your purchasing process start to finish, that'd help tremendously. Just drop them in an imgur.com album or something.

The `no protocol` issue you got was due to the lack of an `http://` in your config's url.

**Comment by Warfacenl** [comment] 2016-03-28 23:33
Let me do that tomorrow, maybe u know this already? 

**When i have my own name in the order i get a popup in chrome **
All Donations for thos order have been resent

Going to other user i get nothing 
- can do /woo check in-game, my char gets it only

**Comment by Warfacenl** [comment] 2016-03-29 23:56
Because of my work i had only a few minutes of checking i made a small video where i show that it isnt working properly  https://youtu.be/gqVJKgkhR-M

**Comment by JayWood** [comment] 2016-03-30 01:17
Great, just what I needed to test this myself. Would you also care to screenshot the commands you're running for the product? Which includes general and variable commands if you wouldn't mind.

I should have time this weekend to test this, as well as a few other bugs.

**Comment by Warfacenl** [comment] 2016-03-30 14:11
Can u tell me what u mean with commands? Srry I am totally new in this my little brother knows everything but he is on holiday

**Comment by TekkitCommando** [comment] 2016-03-30 14:58
The commands sent when someone buys the package

**Comment by JayWood** [comment] 2016-03-30 17:19
@Warfacenl Edit the product the user is purchasing in the video, then below you should see something similar to these images: https://wordpress.org/plugins/woominecraft/screenshots/

I need that screenshot of the commands.

**Comment by Warfacenl** [comment] 2016-03-30 23:03
Oke, i did add a variation "test command for 1 year" uhm ordered the same item for both accounts at same time: this is what i get in the console

[01:00:30 ERROR]: [WooMinecraft] No results for the following players: WARFACENL, Pietertj33
[01:00:40 INFO]: [WooMinecraft] Donations updated.
[01:00:41 INFO]: Given [Diamond] * 1 to WARFACENL
[01:00:41 INFO]: Unknown command. Type "/help" for help.
[01:00:50 INFO]: [WooMinecraft] Donations updated.
[01:00:51 INFO]: Unknown command. Type "/help" for help.

**Comment by JayWood** [comment] 2016-04-04 14:02
@Warfacenl - Try out the latest release of the WP version ( if you don't already have it updated ) - https://github.com/WooMinecraft/woominecraft-wp/releases/tag/1.0.4

**Comment by Hoki-gcav** [comment] 2016-04-04 17:23
I would like to also state that this is happening to me, and I don't want to move to buycraft after the work i put into that woo commerce store ._.

The item or rank is given to my players 2-4 times or so before finally stopping, sometimes days after the actual purchase. I have no idea why this is happening, config seems to be all in check after I made sure it was air tight after checking it over with a fellow WooCommerce user. I am also not getting any errors in console regarding WooCommerce, just that after a purchase has been completed the automatic check won't pick it up for at least an hour or 2 before it goes wild and gives people loads of their items.

Here is the config:
`lang: en
update_interval: 300
url: http://www.gcav.eu
key: fc6b68cd750c4a1b84fa6285f6e79546
`
(The key is not my real key, for the purposes of security)

**Comment by TekkitCommando** [comment] 2016-04-04 18:50
@Hoki-gcav  @Warfacenl WooMinecraft for WordPress was updated!

**Comment by JayWood** [comment] 2016-04-04 21:14
The issue of 'giving items, until finally stopping' was solved in the latest commit on WooMinecraft here: WooMinecraft/woominecraft-wp#04576ef91ebf2b35f94693f8ab23dc793f585535

The problem was the java code was sending the data as a string, and not an array.  However, the array datatype was assumed on the WordPress side.  I updated the code to explode and sanitize the string before working with it. This proved to be working for me.

During initial testing, we only tested with one player, which is why the issue never arose, to put it in dev terms ( as if it wasn't already ) the code looked like this to PHP:

`array( "player name", " player two" )`

Notice the space before the second value, that was indeed the entire issue. This **is** fixed in the latest issue which you can [download from .org](https://wordpress.org/plugins/woominecraft/) or update manually in your WordPress dashboard.

@Hoki-gcav @Warfacenl

**Comment by Hoki-gcav** [comment] 2016-04-04 21:33
Yes, thanks i just updated. :)

**Comment by Warfacenl** [comment] 2016-04-04 21:42
Thank you, gonna test it after my work.

**Comment by Hoki-gcav** [comment] 2016-04-04 23:58
Ok, it did it again just got a guy who joined and got a weapon he bought a few days back, i will see if it continues.

**Comment by JayWood** [comment] 2016-04-05 00:11
@Hoki-gcav chances are that was due to the faulty updates - if you run `/woo check` again, you should see that it's fine. If not, post a copy of your log from when the command was ran.

**Comment by Hoki-gcav** [comment] 2016-04-05 07:59
Yeah, ok, i will keep you posted if it happens again with an item that has already been processed after the update.

**Comment by Hoki-gcav** [comment] 2016-04-05 12:42
Ok it was a little different this time, a guy bought like 50 dollars worth of items and all the commands executed at the same time but one of the commands ran twice with the others and he ended up getting 2 of one item by mistake.

**Comment by Hoki-gcav** [comment] 2016-04-05 12:48
Also something a little bit off topic, on the WooCommerce email's, is there a way I can add the username field anywhere, like a placeholder? I want to see the username of the person who donates so I can go on and thank them without having to sign into my site and look up the order each time.

**Comment by TekkitCommando** [comment] 2016-04-05 12:50
WooCommerce email placeholders hmmm @JayWood might know. As far as that bug working except for one item. I woudn't know the cause of that :P I can't look into it because I am class and I will have class till May 29th but after that I will be working on this again.

**Comment by Hoki-gcav** [comment] 2016-04-05 12:55
Alright thanks ;3

**Comment by Hoki-gcav** [comment] 2016-04-05 13:53
Well when you are free, your welcome to come on my server and I can give you any and all resources you would need to see what is going wrong.

**Comment by JayWood** [comment] 2016-04-05 18:23
@Hoki-gcav Yea I can actually add that to your email for you via the code :) - Add that as an issue here: https://github.com/WooMinecraft/woominecraft-wp/issues and I'll tag it for the next release.

As for looking into the 'one item' issue, it's possible the command saved twice, or that the item count for that item was off. However, the only way for me to know is to get complete access to your server, this includes your database, wordpress site, and minecraft server as op.

**IF** you want to take that leap of faith I can definitely look into it this week and of course I can screenshare ( via skype ) if you need while I work on it. I assure you however, I'm not a kid, I code for a living, so I wouldn't nuke your server lol.

If you'd like to do that, I'd be more than willing to look into it for you, just add me on skype: **jjswebs** and we'll setup a time to meet online.

Looking through the code, it literally goes from point A to point B, there's no point in which a 'double processing' action could occur. The only thing I could think of is that the commands for that item reside both in the 'General' tab, and in the 'Variation' of the product ( if it is a variable product ).

If in fact it's NOT a variable product, I have NO idea how it would have two commands for the same item, and will need to investigate.

**Comment by Hoki-gcav** [comment] 2016-04-05 20:34
Yea that would be fine, have no issues with that. I make backups of everything and I change all passwords weekly so no risk on my end. Everything is hosted on the same server so giving you access to all that is easy. I got PHPMyAdmin running if that would be easier for you when looking at the mySQL but i'd have to add your ip to the apache whitelist.

**Comment by JayWood** [comment] 2016-04-06 02:47
@Hoki-gcav Sent you a skype request, if an email is required I can send you one from my personal ( non gmail ) email. But I'm sure we can has all the details over skype.

I'm usually available anytime after 5pm EST ( UTC -5 ) as I work 9-5, Thursday's I'm usually offline all day.

**Comment by JayWood** [comment] 2016-04-07 13:34
@Hoki-gcav any updates on this? Was it a config issue for that item's commands?

**Comment by JayWood** [comment] 2016-05-07 05:55
Closing issue, no response in 30 days.

**Closed by JayWood** 2016-05-07 05:55 UTC
Labels: Bug: Woo Minecraft (Java)
