### ISSUE TITLE
tatus code is not 200 got: 503

### ISSUE THREAD

**Issue by eric2788** [WooMinecraft/WooMinecraft#151] opened 2017-05-07 04:49 UTC
//////////////////   
// You can delete the following   
// In order for me to better serve your support request, please fill out the following information.   
// Please use pastebin http://pastebin.com/ or gists https://gist.github.com/ for your logs, DO NOT PASTE them in a support request.   
// Refer to the following link for proper config.yml setup fields - https://github.com/WooMinecraft/WooMinecraft#config   
// 
// YOU MUST ACTIVATE DEBUG IN YOUR CONFIG AND PROVIDE THAT LOG
//   
// Fields below this line are required - failure to fill these in will result in your issue being tagged low-priority.   
/////////////////   

**Log Link: 

```
[WooMinecraft] Status code is not 200 got: 503
[12:41:40] [Craft Scheduler Thread - 152/WARN]: java.lang.Exception: Status code is not 200 got: 503
[12:41:40] [Craft Scheduler Thread - 152/WARN]: 	at com.plugish.woominecraft.Util.RcHttp.request(RcHttp.java:50)
[12:41:40] [Craft Scheduler Thread - 152/WARN]: 	at com.plugish.woominecraft.WooMinecraft.check(WooMinecraft.java:129)
[12:41:40] [Craft Scheduler Thread - 152/WARN]: 	at com.plugish.woominecraft.Util.BukkitRunner.run(BukkitRunner.java:18)
[12:41:40] [Craft Scheduler Thread - 152/WARN]: 	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:58)
[12:41:40] [Craft Scheduler Thread - 152/WARN]: 	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
[12:41:40] [Craft Scheduler Thread - 152/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[12:41:40] [Craft Scheduler Thread - 152/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[12:41:40] [Craft Scheduler Thread - 152/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)

```
### Server Information:
* **Host: not open yet
* **URL: http://mc.hypernite.com/
* **WordPress URL: http://mc.hypernite.com/

### Config.yml
* **url: http://mc.hypernite.com/

**Comment by spannerman79** [comment] 2017-05-07 05:21
This is not a plugin issue - more an issue with your wordpress/hosting

/google http 503 status code

**Comment by spannerman79** [comment] 2017-05-07 05:24
And possible dupe of https://github.com/WooMinecraft/WooMinecraft/issues/150#issuecomment-296389994

**Comment by JayWood** [comment] 2017-05-08 04:45
+1 for this, 503 errors are an issue w/ your host, not the plugin.

**Closed by JayWood** 2017-05-08 04:45 UTC
