### ISSUE TITLE
Commands not forwarding to server and /woo check error

### ISSUE THREAD

**Issue by doitliketyler** [WooMinecraft/WooMinecraft#79] opened 2016-03-21 20:41 UTC
Hey there. I followed the setup instructions thoroughly and can't seem to figure out whats going on. When I purchased a package through my donation store the commands never make it to the server and if I use the /woo check command I get this error:

http://pastebin.com/HwNHG4gp

Any ideas? I'm running on Spigot 1.9

**Comment by JayWood** [comment] 2016-03-21 20:45
We have not tested for 1.9 yet, but the error is `21.03 16:38:19 [Server] ERROR [WooMinecraft] Server returned HTTP response code: 406 for...` which is the same error as #71 

We've not been able to replicate the error however, so debugging is not easy to say the least.

Could you provide detailed information as to your server setup? Basically everything but your password, essentially the more information you can provide the better.

**Comment by JayWood** [comment] 2016-03-21 20:50
ALso, check your URL `http://curiocore.comoo_minecraft=check&key=d9a4813b1a5d4b27ae5068d8bf60248c` looking at that URL there's a problem (obviously) - can you paste your config exactly as you have it?

**Comment by doitliketyler** [comment] 2016-03-21 20:55
Sure. I'll do my best. I'm running 5 Spigot 1.9 servers on a Bungeecord network. WooMinecraft is only running on my lobby server.

Startup console log: http://pastebin.com/BwUf2i6w
WooMinecraft config: http://pastebin.com/5XrkVwEK
Plugin List: http://pastebin.com/CtMEky10

**Comment by JayWood** [comment] 2016-03-21 22:46
Your config looks fine and it looks like the error we got back from your server wasn't handled. SO with that being said, this is definitely a bug, however, still unsure if it's 1.9 related or not.

For sanity's sake, would you mind wrapping your URL in double quotes in the config and giving it a go again?

**Comment by doitliketyler** [comment] 2016-03-21 22:57
Alright, I added the double quotes to the URL and that fixed the command error but when purchasing a package the commands are still not forwarding to the server. I just quadrupled check to ensure my game key was matching as well. Here is a screenshot of the test product I set up:

http://imgur.com/UghnN8a

I'm really hoping that I missed something blatantly obvious.

**Comment by TekkitCommando** [comment] 2016-03-21 23:31
@JayWood Good news buddy, I got a spring break :D Time to destroy these bugs.

**Comment by TekkitCommando** [comment] 2016-03-21 23:33
@JayWood A little off topic but my PHP courses are going great, got 100% on all my quizzes and I am working on a CMS as my end of course project.

**Comment by JayWood** [comment] 2016-03-22 00:29
@doitliketyler great, since that fixed the error, now the only thing left is to figure out the order issue. Which, thankfully MIGHT be fixed by setting the order to `completed`.

In another issue a week or so ago, a user suggested ticking the 'downloadable' checkbox for a product and try to re-purchase it.  Would you care to try that?

**Comment by doitliketyler** [comment] 2016-03-22 00:38
Just tried both and unfortunately still no commands are being forwarded.

**Comment by JayWood** [comment] 2016-03-22 00:47
Okay well I feel like we're super close, would you care to provide a copy of your log right after you run the command ( a new log )

**Comment by doitliketyler** [comment] 2016-03-22 00:50
Sure. It simply says:

`21.03 20:49:51 [Server] INFO [WooMinecraft] No donations for online users.
21.03 20:49:50 [Server] INFO doitliketyler issued server command: /woo check`

**Comment by JayWood** [comment] 2016-03-22 00:51
So, no error, which is good, okay give me a few I want to try something

**Comment by JayWood** [comment] 2016-03-22 01:06
Well good news is, I can get a result, so the order is definitely there. Using my nifty little program, this is what the java plugin SHOULD see ( pending deliveries ):

![45ece303af976ee92490110852940887](https://cloud.githubusercontent.com/assets/2303074/13939029/60a1b358-efa7-11e5-8787-ec092c3a9c69.png)

However, @TekkitCommando [THIS if statement](https://github.com/WooMinecraft/WooMinecraft/blob/master/src/main/java/com/plugish/woominecraft/WooMinecraft.java#L167) isn't being passed through. And the ONLY way I can see that happening is if the content type isn't being sent as `x-www-form-urlencoded` from the MC server to WordPress, as evident in this request ( notice I sent as form-data and not form-urlencoded ): 

![913c99c8f2f1c4c57eded79f1d12a8aa](https://cloud.githubusercontent.com/assets/2303074/13939134/6cdc8854-efa8-11e5-8d69-40e7a6f98335.png)

Also @doitliketyler are you using the latest WP plugin version? I'm almost positive 'request' data wouldn't be an array object in the second screenshot, I thought I fixed that?!

**Comment by doitliketyler** [comment] 2016-03-22 01:08
I am indeed running the latest version of Wordpress.

**Comment by TekkitCommando** [comment] 2016-03-22 01:11
If the check function is being called the only way that if statement wouldn't be ran is if there is an error in it but if there was, the plugin should have had other problems even when it was being compiled. Basically the Java code must be always seeing it as false. I will work with the check function and get back to you :)

**Comment by TekkitCommando** [comment] 2016-03-22 01:25
@JayWood Do you think Cache data of some kind is causing problems, about 200 people have downloaded WooMinecraft from Bukkit/Spigot and only a few have problems or maybe they just don't post an issue, might be handy to code metrics for the plugin.

**Comment by TekkitCommando** [comment] 2016-03-22 01:26
So we can see online servers that are using the plugin

**Comment by TekkitCommando** [comment] 2016-03-22 01:28
Either it's cache data or for some reason its just not finding the success boolean to ever be true for some people there's nothing wrong with the code. The only thing I can see that may be a problem is where it says if(null == json) instead of if(json == null) but that's just because I am OCD.

**Comment by JayWood** [comment] 2016-03-22 01:36
hehe, well in WordPress we call those Yoda conditionals, and it's a standard, but that wouldn't be the issue since conditionals work both ways.

Also, if that was indeed the cause it would fail before even hitting line 212, where it outputs the string to the log.

I think we need to code in a 'debug' option at this point.  It will help alleviate the back-and-forth between us and the end-user simply by saying `turn on debug and give us your log after the command is ran`.

The problem right now is that without 'physically' getting into @doitliketyler server ( both wordpress and MC ) our only real option is to do a sort of global debug.

**Comment by JayWood** [comment] 2016-03-22 01:37
@TekkitCommando I think I'll go ahead and get started on the debug flag, I have an idea where to implement all of them.

**Comment by TekkitCommando** [comment] 2016-03-22 01:43
@JayWood Ok, post if you need assistance, I am just reading the PHP that makes up the WP plugin so I can get a feel of your wizardry since I am new to PHP and have never coded any WP plugins haha

**Comment by JayWood** [comment] 2016-03-22 02:10
@doitliketyler Give this jar file a go, and let me get a copy of that log after the command is ran, a fresh jar just for you :smile: 

Before you install it, go into the config and add this line
```
debug: true
```

This will turn on debugging for the plugin.

[WooMinecraft-1.0.5-RC1.jar.zip](https://github.com/WooMinecraft/WooMinecraft/files/183410/WooMinecraft-1.0.5-RC1.jar.zip)

**Comment by TekkitCommando** [comment] 2016-03-22 02:12
If this fixes his problem then I will add the jar to the Spigot and Bukkit sites.

**Comment by JayWood** [comment] 2016-03-22 02:13
@TekkitCommando wait until I make an 'official' release via github, I have more things I want to add :smile: and this won't `fix` the issue, it will merely give me more information.

**Comment by TekkitCommando** [comment] 2016-03-22 02:14
Idk, stranger things have happened but alright haha

**Comment by doitliketyler** [comment] 2016-03-22 02:18
Here ya go: http://pastebin.com/ft6D9AKg

**Comment by TekkitCommando** [comment] 2016-03-22 02:22
It's always the names

**Comment by JayWood** [comment] 2016-03-22 02:29
@TekkitCommando if you look at that log, you'll see the same broken URL `http://www.curiocore.comoo_minecraft=check&key=d9a4813b1a5d4b27ae5068d8bf60248c`

Take a look tat Connection in the construct line 32, is this not a safe way to do this?
`url_path + "?woo_minecraft=check&key=" + key` It's basic concatiation so I'm not sure of the issue here. The ONLY reason we'd get code 7 ( this error ) is if the proper data isn't sent.

**Comment by JayWood** [comment] 2016-03-22 02:31
@doitliketyler Just one more thing my friend and we should be able to take it from here. Would you care to uninstall your version of the WordPress plugin and install this one? https://github.com/WooMinecraft/woominecraft-wp/archive/dev.zip

**Comment by JayWood** [comment] 2016-03-22 02:33
fingers crossed - it's a java quick-win by just encoding the URL

**Comment by TekkitCommando** [comment] 2016-03-22 02:37
@JayWood the concatenation of the URL should be fine and it's pretty commonly used. And yes as long as proper data is sent there should no problems.

**Comment by TekkitCommando** [comment] 2016-03-22 02:40
I'm not sure why his log says the url is missing the ?w unless in the concatenation either you I was typing to fast when doing something and mistyped.

**Comment by JayWood** [comment] 2016-03-22 02:42
Nope, def wasn't me, tested before I created the jar, I got a full url :)

**Comment by doitliketyler** [comment] 2016-03-22 02:45
Voila http://pastebin.com/kc6stUTs

**Comment by JayWood** [comment] 2016-03-22 02:51
@doitliketyler yep, names isn't getting $_POST'd @TekkitCommando that's where we need to start :cry: thanks for the help

**Comment by TekkitCommando** [comment] 2016-03-22 03:12
@JayWood have you got if(isset($_POST['whatevs'])) and if it returns false can echo a message? Might be a good place to start?

**Comment by doitliketyler** [comment] 2016-03-22 03:12
No problem

**Comment by JayWood** [comment] 2016-03-22 03:31
@TekkitCommando $_REQUEST is a combination of $_GET and $_POST parameters in PHP, which is where [this snippet](https://github.com/WooMinecraft/woominecraft-wp/blob/dev/functions.php#L261) comes in handy.

It returns all $_POST and $_GET params in the debug so we got this back from @doitliketyler : 
```
{
    "data": {
        "code": 7,
        "msg": "Method or Names parameter was not set.",
        "request_data": {
            "key": "d9a4813b1a5d4b27ae5068d8bf60248c",
            "woo_minecraft": "check"
        }
    },
    "success": false
}
```

Notice the lack of the `names` key under `request_data` - however, on MY server, that's not a problem, see my log where I **forced** the error:
```
{
    "data": {
        "code": 7,
        "msg": "Method or Names parameter was not set.",
        "request_data": {
            "key": "f7dc6429cfbc4785891ed8ae9c4472aa",
            "names": "SprinkledPanda",
            "woo_minecraft": "check"
        }
    },
    "success": false
}
```

The issue is content the `names` key isn't being sent at all from Java, which leads me to believe the issue is with [getPlayerResults](https://github.com/WooMinecraft/WooMinecraft/blob/master/src/main/java/com/plugish/woominecraft/Connection/Connection.java#L102) or maybe [processNames](https://github.com/WooMinecraft/WooMinecraft/blob/master/src/main/java/com/plugish/woominecraft/Connection/Connection.java#L81)

I know we're not returning at [line 114](https://github.com/WooMinecraft/WooMinecraft/blob/master/src/main/java/com/plugish/woominecraft/Connection/Connection.java#L114) and we're definitely getting the input stream - it's just like processNames isn't posting the data.

**Comment by JayWood** [comment] 2016-03-22 03:33
@doitliketyler one more question, did you have more than one player on? If so, I MIGHT know what caused it?

**Comment by TekkitCommando** [comment] 2016-03-22 03:37
@JayWood I see, you learn something new everyday :+1:

**Comment by doitliketyler** [comment] 2016-03-22 03:38
I was the only player on the server.

**Comment by JayWood** [comment] 2016-03-22 03:40
@doitliketyler okay thanks man - It's getting late here, so I'm gonna crash for the night, but I'll look more into this tomorrow. **hopefully** you're available tomorrow to do more testing if possible

**Comment by doitliketyler** [comment] 2016-03-22 03:42
I'm a freelance developer so unless I get a project suddenly I should be around.

**Comment by TekkitCommando** [comment] 2016-03-22 03:42
@JayWood looking at the code on github I see no problem, though connections to web based data in Java has always been one of my weaker abilities. I am off my computer tonight but I can definitely mess with the code in my ide first thing in the morning.

**Comment by JayWood** [comment] 2016-03-22 20:42
@TekkitCommando I'm going to look into different methods of posting data via Java, I think the posting method is screwy, while it works for some, it obviously doesn't for others.

Was looking at some examples of apache's HttpPost class here: http://www.programcreek.com/java-api-examples/org.apache.http.client.methods.HttpPost looks promising and WAY easier to use, but we'd have to include the library in the plugin.

I'm not against it especially since it's very similar to how PHP handles the posting of data so I'm going to add the lib to the plugin, compile it, and rework a few things on a separate branch and see where it gets us.

**Comment by TekkitCommando** [comment] 2016-03-23 02:58
@JayWood Ok sorry didn't reply earlier just got access to a computer. We may need to get our libraries in a maven repo so we can easily include the dependencies.

**Comment by JayWood** [comment] 2016-03-23 15:50
Not necessarily, we aren't really making libs ( aside from one or two files, connections and I believe another ) - and I'm not sure one file really warrants a full repo unless of course our java code was made with an API in mind ( where other users could hook into it ).

However, I found this nifty thing really late last night - basically it uses maven to include libs at runtime [Maven Shade](https://maven.apache.org/plugins/maven-shade-plugin/) by just adding deps and setting the scope to 'compile'.

So, short of it, I'll be able to include Apache Http libs in the plugin without any huge issues.

**Comment by TekkitCommando** [comment] 2016-03-23 16:36
@JayWood Alright worth a try

**Comment by doitliketyler** [comment] 2016-04-07 04:37
Hey guys. Just curious to know if there was any progress here. I noticed the new release on Wordpess and updated it but my issue still persists.

**Comment by JayWood** [comment] 2016-04-07 13:31
@doitliketyler Not as of late - been really busy myself lately. However I'd LOVE to get this fixed, or at the very least figure out the exact cause. 

We know that the actual names isn't being posted to your server, and I know that's where to start. What I would 'like' to do is get access to your Minecraft and Wordpress servers via FTP so I can upload/download files as needed and be able to debug this more in-depth. [Wordpress IS my day job](https://webdevstudios.com/team/jay-wood/) so I assure you I'm not juvenile about development. If you can take that leap of faith, hit me up on skype: **jjswebs** and we'll hash out a time to do this.

IF that's not possible, what I can do at this point is drop in more debug logs, and hopefully see exactly why the name posting is failing, if at all. The problem is, the code lets Java talk to PHP, so it could be a server config on the PHP side of things.

**Closed** 2016-05-25 03:21 UTC
Labels: Bug: Woo Minecraft (Java)
