### ISSUE TITLE
Status Always Empty

### ISSUE THREAD

**Issue by TekkitCommando** [WooMinecraft/WooMinecraft#15] opened 2015-08-08 21:49 UTC
I don't know if this is my fault or actually a bug, I am looking into it but for now its a bug.

@JayWood might know whats wrong but just in case he is really busy and since there is no reason to disturb him I will consult with my php programming friend @phillmac for now :)

**Comment by TekkitCommando** [comment] 2015-08-09 15:46
I am still looking into whats causing this, but I wont be able to look into it in depth until Tomorrow :)

**Comment by TekkitCommando** [comment] 2015-08-10 12:19
@phillmac believe he's found the problem and is gonna be doing some updates to the Java and PHP, He's identified a problem with the Java Code not wanting to communicate with the PHP Code and/or vice versa.

**Comment by JayWood** [comment] 2015-08-14 03:35
@TekkitCommando @phillmac What do you mean by `status` it's been SO long since I looked at the plugin, but I can definitely give some insight provided more information can be given.

**Comment by JayWood** [comment] 2015-08-14 03:50
Figured it's best that I elaborate on the process of contacting WP from the MC instance, so here it goes:
1. The MC server contacts the WP server passing the url parameters of `woo_minecraft` and `key` 1. The main JSON data is handled in `WordPress/minecraft_woo/inc/main.class.php` [line #31](https://github.com/WooMinecraft/WooMinecraft/blob/master/WordPress/minecraft_woo/inc/main.class.php#L31)
1. IF the `woo_minecraft` url parameter is empty, it simply returns the function, doesn't send anything, though it should and I need to fix that for ya!

The issue may be here, since the only valid parameter it looks for is `update`, if another string is present in the value it will default to the else statement on line 80, which then looks for names parameter.

There's a lot of things I'd like to do differently but I don't want to step on @phillmac's toes, so let me know when you guys are in a good spot and I'll begin re-working the WordPress portion of the plugin!

**Comment by JayWood** [comment] 2015-08-14 04:51
Check the commits and the wp-dev branch for all WordPress related changes/optimizations.
[this](https://github.com/WooMinecraft/WooMinecraft/commit/7b87bba9c1dcf951734f75257971c12cd2426d6b#diff-9fcab18b4a6c0c50d0af16062a6e3a98R37) may have fixed this issue, please test.

[Branch Commits](https://github.com/WooMinecraft/WooMinecraft/commits/wp-dev)
[wp-dev Branch](https://github.com/WooMinecraft/WooMinecraft/tree/wp-dev)

**Comment by phillmac** [comment] 2015-08-14 05:04
What was happeneing before hand was that $_REQUEST did not ever have a
"names" key, only the  "method" and  "key". Ill test the new commits to see
if the problem is resolved. .. unless the "names" key is being unset
somewhere I don't  think any amount of rewriting the WP side of things is
going to make it appear

~ Phill

**Comment by phillmac** [comment] 2015-08-14 05:08
Whar that would cause is the sql where clause to be empty and therefore return an empty result set.

**Comment by JayWood** [comment] 2015-08-14 05:15
IF the names key is empty you should've got [false](https://github.com/WooMinecraft/WooMinecraft/blob/wp-dev/WordPress/minecraft_woo/inc/main.class.php#L98) as a string for the status, but with the additions of the [isset check](https://github.com/WooMinecraft/WooMinecraft/blob/wp-dev/WordPress/minecraft_woo/inc/main.class.php#L95) that will no longer be possible, if names isn't set, you'll get nothing.

Just made a commit for a final fall back so you guys can at least check status messages if all else fails [4af5597](https://github.com/WooMinecraft/WooMinecraft/commit/4af5597b4f5b885ee3480d405e303165bad54cc1)

**Comment by TekkitCommando** [comment] 2015-08-15 19:39
Thanks for the help, i am back btw c: sorry for disappearing friends :P

**Comment by TekkitCommando** [comment] 2015-08-16 06:27
Cuz the updates might fix it xD

**Comment by JayWood** [comment] 2015-08-16 16:13
@TekkitCommando [This Commit](https://github.com/WooMinecraft/woominecraft-wp/commit/72ff49ea5259b8b9da2e3badb6f1602ba33224e1) may also help, though you'll need to accommodate the new JSON response structure.  I added error codes you can check for, instead of having to worry about what the error was.

Also, can you give me a little insight on how to compile this java, so I can test the WordPress side of things again?

**Comment by TekkitCommando** [comment] 2015-08-16 17:11
Well I use Intellij and most people use eclipse :P In eclipse you can add the source manually then compile OR.. You can download intellij and use the git cloning feature it will reuse my .iml files and you can compile right away :)

Tell me whether you get Intellij or you want to use eclipse and i will help further :)

**Comment by TekkitCommando** [comment] 2015-08-16 17:13
Also I will be working on the new JSON request feature right after I make WooMinecraft translatable which wont take but an hour or 2 :)

**Comment by JayWood** [comment] 2015-08-16 18:10
I use eclipse for compiling.  But i'm used to compiling forge with gradle, it's been so long since I've messed with bucket.

**Comment by TekkitCommando** [comment] 2015-08-16 20:08
Might need to make it maven at some point

**Comment by TekkitCommando** [comment] 2015-08-16 20:15
I will make a video later of how to do it, it seems easiest instead of typing a bunch of stuff :)

**Comment by JayWood** [comment] 2015-08-16 20:58
That's fine, I can fake the data until then.

**Comment by JayWood** [comment] 2016-01-24 20:30
Closing, as ticket is way off track and way out of date.  Will re-open if the need arises.

**Closed by JayWood** 2016-01-24 20:30 UTC
Labels: Bug: Woo Minecraft (Java), Bug: Woo Minecraft (PHP), Possibly Fixed (Not Tested)
