### ISSUE TITLE
Sponge API Support

### ISSUE THREAD

**Issue by CrankySupertoon01** [WooMinecraft/WooMinecraft#184] opened 2018-10-21 17:58 UTC
Bukkit is very outdated. After the DMCA it feel very much apart. Alot of servers are running very strongely, using the Sponge API. It is very similar to Forge on how the code base is.

The flexibility of sponge and how it interacts with forge is the only reason i use buycraft. Why because sponge only have Enjin and Buycraft. If you could port this to the Sponge API, i feel like this might take off, since the sponge api is more up to date, and WooMinecraft on it can mean more stable wordpress sites with minecraft mods

**Comment by spannerman79** [comment] 2018-10-21 21:09
> Bukkit is very outdated. After the DMCA it feel very much apart. Alot of servers are running very strongely, using the Sponge API. It is very similar to Forge on how the code base is.

Oh really? I call bullshit.  [SpigotMC & Spigot](https://www.spigotmc.org/) is one of the most used servers.  Not to mention [Cuberite](https://cuberite.org/) that runs on just about anything.  So already your OP is on very shaky ground.

> The flexibility of sponge and how it interacts with forge is the only reason i use buycraft

Hm lets see, well myself as well as **many** others that do use a proxy use Hexacord and we don't have an issue with a mixed Spigot, Sponge and Cauldron based network.

The time you took to write that dribble you could have easily searched for "sponge" in this repo and you would have seen #125

**Comment by JayWood** [comment] 2018-10-21 22:07
Breathe @spannerman79 breathe... I feel like there's home history here I don't know about lol...

However, I have to side with spanner here, though in a bit less hostile manner haha - Bukkit yea, may not be as widely used as it once was, but it's still very much a part of the Spigot build process. So I would hardly consider it outdated.

In order for me to work on the sponge API integration, I need time, and time translates to money in my industry, so I need to have a nack to just dive into that feature, which I haven't yet.

Closing this as a duplicate of the previously mentioned issue.

**Closed by JayWood** 2018-10-21 22:07 UTC
