### ISSUE TITLE
!Important! WooMinecraft gives error/wont work!

### ISSUE THREAD

**Issue by evanmcclan** [WooMinecraft/WooMinecraft#149] opened 2017-04-19 23:13 UTC
My Problem: 
_WooMinecraft wont execute commands/detect purchases correctly. At first, upon running the check command, it doesn't return any actions (even if there are purchases). then after a server restart, running the check command prompts an internal error message, the full log is linked in this document._

Please help me fix this issue ASAP, donors are not able to get their perks because of this error.

Server Information:
Server IP: Play.OneBigNation.Net
Server Version: This server is running CraftBukkit version git-Spigot-21fe707-e1ebe52 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)
Plugin Jar Version: WooMinecraft-1.1.1-B1.8.8-R0.1.jar **(Yes its only this 1 jar installed. not multiple)**
WordPress URL: https://onebignation.net/
WordPress WooMinecraft Version: **Version 1.1 | By Jerry Wood**

Woo-Minecraft Config.yml setup: https://pastebin.com/V6pTieRj
Console Error Log Link: https://pastebin.com/mFU42mAA

**Comment by JayWood** [comment] 2017-04-22 02:05
The error:
```
19.04 17:57:36 [Server] INFO at com.plugish.woominecraft.Commands.WooCommand.onCommand(WooCommand.java:28) ~[?:?]
19.04 17:57:36 [Server] INFO at com.plugish.woominecraft.WooMinecraft.check(WooMinecraft.java:137) ~[?:?]
19.04 17:57:36 [Server] INFO Caused by: java.lang.NoClassDefFoundError: Could not initialize class org.json.JSONObject
```

Org.JSON is included via the Maven build, and this was tested on 1.8 Bukkit, not spigot, which may be the cause of the issue? 

I realize the urgency here, but you have to understand, this is open-sourced software, I work 9-5 every week day, I do not get paid to work on this, so therefore it's done on my free time, or if I have a nack to dive in.

With that being said, can you give me a link to where you downloaded your server jar?

**Comment by evanmcclan** [comment] 2017-04-24 18:51
@JayWood since we are hosted by Beastnode, we do not use buildtools to get our server jars, they offer it in a list of selectable jars that they have pre-installed in their online control panel. 

here is a screenshot:
http://prntscr.com/f0cg6d
http://prntscr.com/f0cguw

if you have any questions let me know (p.s. sorry about my late reply)
Thanks for helping :)

**Comment by JayWood** [comment] 2017-04-24 20:05
@evanmcclan hrm, okay, I'll see if I can find a version of that Jar, but if it's custom compiled, chances are I'll be of zero help. Are you able to FTP in and grab the Jar file at all?

**Comment by evanmcclan** [comment] 2017-04-25 14:25
@JayWood Here are download links to the 2 jars that are located in the FTP, hope this helps. Once again, thanks.

https://www.dropbox.com/s/ia9k35fridgz2r6/spigot_1.8.8_latest.jar?dl=0

https://www.dropbox.com/s/vxsmfeegytpzpii/spigot_latest%20%281%29.jar?dl=0

**Comment by TekkitCommando** [comment] 2017-04-25 14:29
Beastnode and other companies just have an auto builder for the new jars using buildtools so everyone still has the same jars.

**Comment by evanmcclan** [comment] 2017-05-03 19:21
@JayWood any hopes of a fix? (just posting so the thread doesn't go inactive and get closed)

**Comment by eric2788** [comment] 2017-05-06 09:04
@JayWood i have some question here
i want to know whether the whitelist worlds option is player need to be online in that world so woomimecraft will execute the purchase command?

**Comment by JayWood** [comment] 2017-05-08 04:46
I won't close it until it's fixed :) no fix yet, still planned though, sorry for the delay, life things!

**Comment by JayWood** [comment] 2017-05-20 14:51
Work is being done to move the client to a full REST API setup - Started here: WooMinecraft/woominecraft-wp#37

**Comment by TekkitCommando** [comment] 2017-05-20 15:00
Nice new pro pic Jay.

**Comment by JayWood** [comment] 2018-06-09 17:59
Latest updates have been tested purely on 1.12.2 Spigot build, no issues arose, closing. Feel free to re-open if it's still an issue.

**Closed by JayWood** 2018-06-09 17:59 UTC
